### ISSUE TITLE
INTERVAL Variable doesnt seem to take any settings

### ISSUE THREAD

**Issue by eklarson66** [jcostom/dnsomatic-update#3]
When setting the INTERVAL Variable to say some like 900 secs, I get an error of 

"Traceback (most recent call last):
  File "/app/dnsomatic-update.py", line 104, in <module>
    main()
  File "/app/dnsomatic-update.py", line 100, in main
    sleep(INTERVAL)
TypeError: 'str' object cannot be interpreted as an integer"

**Comment by jcostom** [comment]
Hey, standby - it's a silly lack of an int() when pulling in the INTERVAL env variable from the container invocation. There will be a new version shortly.

**Comment by jcostom** [comment]
Ok, v3.4.5 is posted, it fixes the problem. Thanks for the report.
